improved file discovery capabilities when arguments specified

diff --git a/awesome-background-changer b/awesome-background-changer
--- a/awesome-background-changer
+++ b/awesome-background-changer
@@ -15,13 +15,20 @@ setWallpaper() {
 # set wallpaper and exit if filenamae supplied
 if [[ "$1" ]]; then
 	if [[ -f "$1" ]]; then
-		setWallpaper "$1"
-		exit 0
+		cd $(dirname $1)
+		image=$PWD/$(basename $1)
+
 	elif [[ -f "$WALLPAPER_DIR/$1" ]]; then
-		setWallpaper "$WALLPAPER_DIR/$1"
-		exit 0
+		image=$WALLPAPER_DIR/$1
+
+	else
+		printf "File not found: %s\n" "$1"
+		exit 1
 	fi
-	exit 1
+
+	printf "Setting wallpaper to %s\n" "$image"
+	setWallpaper "$image"
+	exit 0
 fi
 
 
